"""
Post-process RST files generated by breathe-apidoc.

1. Adds :allow-dot-graphs: to every '.. doxygenfile::' directive.
2. Adds :maxdepth: 1 to every '.. toctree::' directive (filelist, structlist).
"""
import os
import sys


def _inject_option(lines, directive, option_line):
    """
    For every occurrence of `directive` (e.g. '.. doxygenfile::'),
    inject `option_line` (e.g. '   :allow-dot-graphs:') right after it,
    unless it is already present within the next few lines.
    Returns (new_lines, was_modified).
    """
    new_lines = []
    modified = False
    for i, line in enumerate(lines):
        new_lines.append(line)
        if line.strip().startswith(directive):
            # Check the next few lines to avoid duplicates
            lookahead = lines[i+1 : i+6]
            if any(option_line.strip() in la for la in lookahead):
                continue
            new_lines.append(option_line + "\n")
            modified = True
    return new_lines, modified


def post_process(root_dir):
    for dirpath, _, filenames in os.walk(root_dir):
        for filename in filenames:
            if not filename.endswith(".rst"):
                continue

            filepath = os.path.join(dirpath, filename)
            with open(filepath, "r", encoding="utf-8") as f:
                lines = f.readlines()

            modified = False

            # 1) Add :allow-dot-graphs: to doxygenfile directives
            lines, changed = _inject_option(
                lines, ".. doxygenfile::", "   :allow-dot-graphs:"
            )
            modified = modified or changed

            # 2) Add :maxdepth: 1 to toctree directives (filelist / structlist)
            if filename in ("filelist.rst", "structlist.rst"):
                lines, changed = _inject_option(
                    lines, ".. toctree::", "   :maxdepth: 1"
                )
                modified = modified or changed

            if modified:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.writelines(lines)
                print(f"  post-process: updated {filename}")


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.getcwd(), "api")
    post_process(target)
