title = "uCommander"
version = "0.2.2"

[[projects]]
name = "Bajaj 2 wheeler"
identifier = "DIET"
can_id = 0xCDA33F1
[[projects.requires]]
field = "VinNo"
default = "DIET_111_15"
type = "string"


[[projects]]
name = "Gradient Sensor"
identifier = "GradSens"
can_id = 0x1BDAA2F1
requires = []

[[projects]]
can_id = 0xdeadbeef
identifier = "Test"
name = "Test Project"
[[projects.requires]]
field = "foo"
type = "string"
default = 10

[[projects.requires]]
field = "bar"
type = "string"

[[projects.requires]]
field = "baz"
type = "string"


