title = "uCommander"
version = "0.3.0"

[[projects]]
name = "TCU (chetak)"
ecu_id = 0x0CDAF133
tester_id = 0x0CDA33F1
nai_protocol = "29B_FIXED_NORMAL"
bit_rate = "500Kbps"

[[projects.requires]]
field = "VinNo"
default = "DIET_111_"
type = "string"
max_length = 17


[[projects]]
name = "Gradient Sensor"
ecu_id = 0x1BDAF1A2
tester_id = 0x1BDAA2F1
nai_protocol = "29B_EXTENDED"
bit_rate = "500Kbps"
requires = []
