title = "uCommander"
version = "0.3.0"

[[projects]]
name = "Bajaj 2 wheeler"
ecu_id = 0x0CDAF133
tester_id = 0x0CDA33F1

[[projects.requires]]
field = "VinNo"
default = "DIET_111_15"
type = "string"


[[projects]]
name = "Gradient Sensor"
ecu_id = 0x1BDAF1A2
tester_id = 0x1BDAA2F1
requires = []

[[projects]]
ecu_id = 0xdeadbeef
tester_id = 0xc0ffee
name = "Test Project"

[[projects.requires]]
field = "foo"
type = "string"
default = 10

[[projects.requires]]
field = "bar"
type = "string"

[[projects.requires]]
field = "baz"
type = "string"


